orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderHistoryListView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name="create"),
    path('', OrderHistoryListView.as_view(), name="history")
]

pages/urls.py
from django.urls import path

from pages.views import ContactCreateView, AboutView, HomeView, LoginView, RegisterView
from products.views import add_to_wishlist

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('blog/', AboutView.as_view(), name='blog'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),
    path('', HomeView.as_view(), name='home')
]

products/urls.py
from django.urls import path

from products.views import ProductsListView, ProductDetailView, CommentCreateView, WishlistListView, \
    CartListView, add_to_cart, add_to_wishlist

app_name = 'products'

urlpatterns = [
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('cart/<int:pk>/', add_to_cart, name='add-cart'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
    path('wishlist/', WishlistListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),
    path('', ProductsListView.as_view(), name='lists'),

]

sotti/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('profile/', include('users.urls', namespace='profile')),
    path('products/', include('products.urls', namespace='products')),
    path('', include('pages.urls', namespace='contact')),
)
# hny$pz4Ve263K-T
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
	<meta name="author" content="CodePixar">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta charset="UTF-8">
	<title>{{ title }}</title>

	<!-- CSS============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	{% block style_scripts %} {% endblock %}

</head>

<body>


    {% include 'layouts/header.html' %}


    {% block content %}
    {% endblock %}


	{% include 'layouts/footer.html' %}

	{% block common_scripts %}{% endblock %}
	<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
	<!--gmaps Js-->
	<script src="{% static 'js/main.js' %}"></script>

	{% block extra_js %}{% endblock %}


</body>

</html>

templates/layouts/cart-modal.html
<!--{% if messages %}-->
<!--    {% for message in messages %}-->
<!--        <div class="toast bg-dark" style="color:#fff; position: absolute; top: 390px; right: 115px; padding:7px; z-index: 99999" data-delay="5000">-->
<!--            <div class="toast-body">-->
<!--                {{ message }}-->
<!--            </div>-->
<!--        </div>-->
<!--    {% endfor %}-->
<!--{% endif %}-->

templates/layouts/footer.html
{% load static %}
{% load i18n %}
<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>{% trans 'About Us' %}</h6>
						<p>
							{% blocktrans %}
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua
							{% endblocktrans %}
						</p>
					</div>
				</div>
				<div class="col-lg-4  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>{% trans 'Newsletter' %}</h6>
						<p>{% trans 'Stay update with our latest' %}</p>
						<div class="" id="mc_embed_signup">

							<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							 method="get" class="form-inline">

								<div class="d-flex flex-row">

									<input class="form-control" name="EMAIL" placeholder="Enter Emaasdil" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
									 required="" type="email">


									<button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
									<div style="position: absolute; left: -5000px;">
										<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
									</div>

									<!-- <div class="col-lg-4 col-md-4">
													<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
												</div>  -->
								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>{% trans 'Follow Us' %}</h6>
						<p>{% trans 'Let us be social' %}</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>

						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
<!--				<p class="footer-text m-0">&lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;-->
<!--Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>-->
<!--&lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;-->
<!--</p>-->
			</div>
		</div>
	</footer>

templates/layouts/header.html
{% load static %}
{% load i18n %}
{% load mytags %}

<header class="header_area sticky-header">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="{% url 'contact:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
						<div class="">
							<ul class="nav navbar-nav navbar-right" style="display:flex;flex-direction:unset">
							<li class="nav-item p-2"><a href="{% url 'products:cart' %}" class="cart"><span class="ti-bag" id="cart_length2">{% get_cart_count request %}</span></a></li>
							<li class="nav-item p-2"><a href="{% url 'products:wishlist' %}" class="wishlist"><span class="ti-heart" id="wishlist_length2">{% get_wishlist_count request %}</span></a></li>
							<li class="nav-item p-2">
								<button class="search"><span class="lnr lnr-magnifier" id="search2"></span></button>
							</li>
						</ul>
						</div>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item {% load active_link_tags %}"><a class="nav-link" href="{% url 'contact:home' %}">{% trans 'Home' %}</a></li>
                      	{% load active_link_tags %}
                        <li class="nav-item {%  if request.path ==  '/products/' %}active{% endif %}"><a class="nav-link {% active_link 'products:lists' %}" href="{% url 'products:lists' %}">{% trans 'Shop' %}</a></li>
                        <li class="nav-item {% if request.path == '/blog/' %}active{% endif %}"><a class="nav-link" href="{% url 'contact:blog' %}">{% trans 'About Us' %}</a></li>
                        <li class="nav-item {% if request.path == '/contact/' %}active{% endif %}"><a class="nav-link" href="{% url 'contact:contact' %}">{% trans 'Contact' %}</a></li>

							<li class="nav-item submenu dropdown">
								{% get_current_language as lang %}
								{% get_available_languages as langs %}
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false"> {{ lang }} <i class="fa fa-caret-down" aria-hidden="true"></i></a>
								<ul class="dropdown-menu">
									{% for l in langs %}
									 {% if l.0 != lang %}
										<li class="nav-item"><a class="nav-link" href="{% get_url_lang request l.0 %}">{{ l.0 }}</a></li>
									 {% endif %}
									{% endfor %}
								</ul>
									<li class="nav-item submenu dropdown">
										{{ user.username }}
								<span href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false" style="cursor:pointer">
									{% if request.user.is_authenticated %}
										{% trans 'Log out' %}
									{% else %}
										{% trans 'Sign in' %}
									{% endif %}
									<i class="fa fa-caret-down" aria-hidden="true"></i></span>
								<ul class="dropdown-menu">
									{% if request.user.is_authenticated %}
								<li class="nav-item"><a href="{% url 'orders:history' %}" class="nav-link"><span class="">{% trans 'History' %}</span></a></li>
<!--								<li class="nav-item"><a href="{% url 'profile:home' %}" class="nav-link"><span class="">Profile</span></a></li>-->
								<li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link"><span class="">{% trans 'Log out' %}</span></a></li>
							{% else %}
									<li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link"><span class="">{% trans 'Sign in' %}</span></a></li>
							{% endif %}
								</ul>
							</li>
							</li>
						</ul>

					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form action="{% url 'products:lists' %}" class="d-flex justify-content-between">
					<input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="{% trans 'Search Here' %}">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
				</form>
			</div>
		</div>
	<div class="search2_input" id="search2_input_box">
			<div class="container">
				<form action="{% url 'products:lists' %}" class="d-flex justify-content-between">
					<input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="{% trans 'Search Here' %}">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search2" title="Close Search"></span>
				</form>
			</div>
		</div>
	</header>

templates/layouts/product_block.html
{% load mytags %}
{% load i18n %}
{% load static %}
{% block content %}
  <a href="{% url 'products:detail' pk=product.pk %}">
                            <div class="single-product">
                                <img class="img-fluid" src="{{ product.image.url }}" alt="">
                                {% if product.is_discount %}
                                <span class="sale"
                                      style="position: absolute;margin-top: 21%;margin-left: -20%;padding: 7px;width: 50px;height: 35px;background-color: #888;color:#fff">sale</span>
                                {% endif %}
                                {% if product.is_new %}
                                <span class="sale {% if product.is_discount %}mt-3{% endif %}"
                                      style="position: absolute;margin-top: 21%;margin-left: -20%;padding: 7px;width: 50px;height: 35px;background-color: #888;color:#fff">new</span>
                                {% endif %}
                                <div class="product-details">
                                    <h6>{{ product.title }}</h6>
                                    <div class="price">
                                        <h6>{{ product.real_price }}som</h6>
                                        {% if product.is_discount %}
                                        <h6 class="l-through">{{ product.price }}som</h6>
                                        {% endif %}
                                    </div>
                                    <div class="prd-bottom">
                                        <a onclick="add_to_cart(this, {{ product.pk }})" class="social-info2">
                                            <span class="lnr">
                                             {% if product|in_cart:request %}
                                                    <span class="ti-bag" style="margin-right:1px"></span>
                                             {% else %}
                                                    <span class="ti-bag" style="margin-right:1px"></span>
                                             {% endif %}
                                            </span>
                                            <p class="hover-text">Cart</p>
                                        </a>
                                        <a onclick="add_to_wishlist(this, {{ product.pk }})" class="social-info2">
                                            <span class="lnr">
                                                 {% if product|in_wishlist:request %}
                                                   <i class="fa fa-heart" style="font-size:17px;margin-right:1px;color:#bd2b44"></i>
                                                {% else %}
                                                    <i class="fa fa-heart" style="font-size:17px;margin-right:1px;"></i>
                                                {% endif %}
                                            </span>
                                            <p class="hover-text">Wishlist</p>
                                        </a>
                                        <a href="{% url 'products:detail' pk=product.pk %}" class="social-info">
                                            <span class="lnr lnr-move"></span>
                                            <p class="hover-text">view more</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </a>


<script>
    function add_to_wishlist(element, pk) {
        $.getJSON('/products/' + "wishlist/" + pk, function (data) {
            if (!data.status) {
               $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-error">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Error
                        </div>
                    </div>`);
            } else {
                if (data.added) {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Added to wishlist
                        </div>
                    </div>`);
                    element.innerHTML = '<span class="lnr" style="background-color:#828bb2;border-radius:50%"><i class="fa fa-heart" style="color:red;font-size:20px;margin-top:6px"></i><p class="hover-text">Added </p></span>'
                } else {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" onclick="MyFunction()" class="close" data-dismiss="alert">&times;</button>
                            Removed from wishlist
                        </div>
                    </div>`);
                    element.innerHTML = '<span class="lnr" style="background-color:#828bb2;border-radius:50%"><i class="fa fa-heart" style="font-size:20px;margin-top:6px"></i><p class="hover-text">Removed </p></span>'
                }
                  $('#wishlist_length').html(data.wishlist_len);
            }
        });
    }
</script>
<script>
    function add_to_wishlist(element, pk) {
        $.getJSON('/products/' + "wishlist/" + pk, function (data) {
            if (!data.status) {
               $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-error">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Error
                        </div>
                    </div>`);
            } else {
                if (data.added) {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Added to wishlist
                        </div>
                    </div>`);
                    element.innerHTML = '<span class="lnr" style="background-color:#828bb2;border-radius:50%"><i class="fa fa-heart" style="color:red;font-size:20px;margin-top:6px"></i><p class="hover-text">Added </p></span>'
                } else {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" onclick="MyFunction()" class="close" data-dismiss="alert">&times;</button>
                            Removed from wishlist
                        </div>
                    </div>`);
                    element.innerHTML = '<span class="lnr" style="background-color:#828bb2;border-radius:50%"><i class="fa fa-heart" style="font-size:20px;margin-top:6px"></i><p class="hover-text">Removed </p></span>'
                }
                  $('#wishlist_length2').html(data.wishlist_len);
            }
        });
    }
</script>
<script>
    function add_to_cart(element, pk) {
        $.getJSON('/products/' + "cart/" + pk, function (data) {
            if (!data.status) {
               $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-error">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Error
                        </div>
                    </div>`);
            } else {
                if (data.added) {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Added to wishlist
                        </div>
                    </div>`);
                    element.innerHTML = ' <span class="ti-bag"></span><p class="hover-text">added to bag +</p>'
                } else {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" onclick="MyFunction()" class="close" data-dismiss="alert">&times;</button>
                            Removed from wishlist
                        </div>
                    </div>`);
                    element.innerHTML = '<span class="ti-bag"></span><p class="hover-text">Removed </p>'
                }
                  $('#cart_length').html(data.cart_len);
            }
        });
    }
</script>
<script>
    function add_to_cart(element, pk) {
        $.getJSON('/products/' + "cart/" + pk, function (data) {
            if (!data.status) {
               $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-error">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Error
                        </div>
                    </div>`);
            } else {
                if (data.added) {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            Added to wishlist
                        </div>
                    </div>`);
                    element.innerHTML = ' <span class="ti-bag"></span><p class="hover-text">added to bag +</p>'
                } else {
                    $('#message').append(`<div style="padding:5px">
                        <div id="inner-message" class="alert alert-success">
                            <button type="button" onclick="MyFunction()" class="close" data-dismiss="alert">&times;</button>
                            Removed from wishlist
                        </div>
                    </div>`);
                    element.innerHTML = '<span class="ti-bag"></span><p class="hover-text">Removed </p>'
                }
                  $('#cart_length2').html(data.cart_len);
            }
        });
    }
</script>
{% endblock %}

templates/layouts/wishlist-model.html
{% if messages %}
    {% for message in messages %}
        <div class="toast bg-dark" style="color:#fff; position: absolute; top: 390px; right: 115px; padding:7px; z-index: 99999" data-delay="5000">
            <div class="toast-body">
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}