orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderHistoryListView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name="create"),
    path('', OrderHistoryListView.as_view(), name="history")
]

pages/urls.py
from django.urls import path

from pages.views import ContactCreateView, AboutView, HomeView, LoginView, RegisterView
from products.views import add_to_wishlist

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('blog/', AboutView.as_view(), name='blog'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),
    path('', HomeView.as_view(), name='home')
]

products/urls.py
from django.urls import path

from products.views import ProductsListView, ProductDetailView, CommentCreateView, WishlistListView, \
    CartListView, add_to_cart, add_to_wishlist

app_name = 'products'

urlpatterns = [
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('cart/<int:pk>/', add_to_cart, name='add-cart'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
    path('wishlist/', WishlistListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),
    path('', ProductsListView.as_view(), name='lists'),

]

sotti/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('profile/', include('users.urls', namespace='profile')),
    path('products/', include('products.urls', namespace='products')),
    path('', include('pages.urls', namespace='contact')),
)
# hny$pz4Ve263K-T
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/checkout.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Checkout</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="single-product.html">Checkout</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
        <div class="container">
<!--            <div class="returning_customer">-->
<!--                <div class="check_title">-->
<!--                    <h2>Returning Customer? <a href="#">Click here to login</a></h2>-->
<!--                </div>-->
<!--                <p>If you have shopped with us before, please enter your details in the boxes below. If you are a new-->
<!--                    customer, please proceed to the Billing & Shipping section.</p>-->
<!--                <form class="row contact_form" action="#" method="post" novalidate="novalidate">-->
<!--                    <div class="col-md-6 form-group p_star">-->
<!--                        <input type="text" class="form-control" id="name" name="name">-->
<!--                        <span class="placeholder" data-placeholder="Username or Email"></span>-->
<!--                    </div>-->
<!--                    <div class="col-md-6 form-group p_star">-->
<!--                        <input type="password" class="form-control" id="password" name="password">-->
<!--                        <span class="placeholder" data-placeholder="Password"></span>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 form-group">-->
<!--                        <button type="submit" value="submit" class="primary-btn">login</button>-->
<!--                        <div class="creat_account">-->
<!--                            <input type="checkbox" id="f-option" name="selector">-->
<!--                            <label for="f-option">Remember me</label>-->
<!--                        </div>-->
<!--                        <a class="lost_pass" href="#">Lost your password?</a>-->
<!--                    </div>-->
<!--                </form>-->
<!--            </div>-->
<!--            <div class="cupon_area">-->
<!--                <div class="check_title">-->
<!--                    <h2>Have a coupon? <a href="#">Click here to enter your code</a></h2>-->
<!--                </div>-->
<!--                <input type="text" placeholder="Enter coupon code">-->
<!--                <a class="tp_btn" href="#">Apply Coupon</a>-->
<!--            </div>-->
            <div class="billing_details">
                <div class="row">
                    <div class="col-lg-12">
                        <h3>Profile</h3>
                        <form class="row contact_form"  method="POST">
                            {% csrf_token %}
                            <div class="col-md-6 form-group a">
                                <span>First name</span>
                                <input type="text" class="form-control" name="first_name" value="{{ form.instance.first_name }}">
                            </div>
                            <div class="col-md-6 form-group p_star">
                                 <span>Last name</span>
                                <input type="text" class="form-control"  name="last_name" value="{{ form.instance.last_name }}">
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <span>Phone number</span>
                                <input type="text" class="form-control" name="phone" value="{{ form.instance.phone }}">
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <span>Email Address</span>
                                <input type="text" class="form-control"  name="email" value="{{ form.instance.email}}">
                            </div>
                              <div class="col-md-12 form-group p_star">
                                  <span>Country</span>
                                <input type="text" class="form-control" name="country" value="{{ form.instance.country }}">
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <span>Country/State</span>
                                <input type="text" class="form-control"  name="state" value="{{ form.instance.state }}">
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <span>Postcode/ZIP</span>
                                <input type="text" class="form-control" id="add2" name="zip" value="{{ form.instance.zip }}">
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <span>Town/City</span>
                                <input type="text" class="form-control" id="city" name="city" value="{{ form.instance.city }}">
                            </div>
                            <div class="col-md-12 form-group">
                                <span>Address</span>
                                <input type="text" class="form-control" id="zip" name="address" value="{{ form.instance.address }}">
                            </div>
                                <div class="creat_account">
                                    <input type="checkbox" id="f-option2" name="selector">
                                    <label for="f-option2">Create an account?</label>
                                </div>
                            </div>
                            <div class="col-md-12 form-group">
                                <div class="creat_account">
                                    <h3>Shipping Details</h3>
                                    <input type="checkbox" id="f-option3" name="selector">
                                    <label for="f-option3">Ship to a different address?</label>
                                </div>
                                <textarea class="form-control" name="message" id="message" rows="1" placeholder="Order Notes"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary float-left">send</button>
                        </form>
                    </div>
<!--                    <div class="col-lg-4">-->
<!--                        <div class="order_box">-->
<!--                            <h2>Your Order</h2>-->
<!--                            <ul class="list">-->
<!--                                <li><a href="#">Product <span>Total</span></a></li>-->
<!--                                <li><a href="#">Fresh Blackberry <span class="middle">x 02</span> <span class="last">$720.00</span></a></li>-->
<!--                                <li><a href="#">Fresh Tomatoes <span class="middle">x 02</span> <span class="last">$720.00</span></a></li>-->
<!--                                <li><a href="#">Fresh Brocoli <span class="middle">x 02</span> <span class="last">$720.00</span></a></li>-->
<!--                            </ul>-->
<!--                            <ul class="list list_2">-->
<!--                                <li><a href="#">Subtotal <span>$2160.00</span></a></li>-->
<!--                                <li><a href="#">Shipping <span>Flat rate: $50.00</span></a></li>-->
<!--                                <li><a href="#">Total <span>$2210.00</span></a></li>-->
<!--                            </ul>-->
<!--                            <div class="payment_item">-->
<!--                                <div class="radion_btn">-->
<!--                                    <input type="radio" id="f-option5" name="selector">-->
<!--                                    <label for="f-option5">Check payments</label>-->
<!--                                    <div class="check"></div>-->
<!--                                </div>-->
<!--                                <p>Please send a check to Store Name, Store Street, Store Town, Store State / County,-->
<!--                                    Store Postcode.</p>-->
<!--                            </div>-->
<!--                            <div class="payment_item active">-->
<!--                                <div class="radion_btn">-->
<!--                                    <input type="radio" id="f-option6" name="selector">-->
<!--                                    <label for="f-option6">Paypal </label>-->
<!--                                    <img src="{% static 'img/product/card.jpg' %}" alt="">-->
<!--                                    <div class="check"></div>-->
<!--                                </div>-->
<!--                                <p>Pay via PayPal; you can pay with your credit card if you don’t have a PayPal-->
<!--                                    account.</p>-->
<!--                            </div>-->
<!--                            <div class="creat_account">-->
<!--                                <input type="checkbox" id="f-option4" name="selector">-->
<!--                                <label for="f-option4">I’ve read and accept the </label>-->
<!--                                <a href="#">terms & conditions*</a>-->
<!--                            </div>-->
<!--                            <a class="primary-btn" href="#">Proceed to Paypal</a>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </section>
    <!--================End Checkout Area =================-->
{% endblock %}

templates/contact.html
{% extends 'layouts/base.html' %}
{% load i18n %}
{% block content %}
		<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>{% trans 'Contact' %}</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'contact:home' %}">{% trans 'Home' %}<span class="lnr lnr-arrow-right"></span></a>
						<a href="#">{% trans 'Contact' %}</a>
					</nav>
				</div>
			</div>
		</div>
	</section>

	<section class="contact_area section_gap_bottom">
		<div class="container">
			<br>
			<div style="position:relative;overflow:hidden;"><a href="https://yandex.uz/maps/10335/tashkent/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">Ташкент</a><a href="https://yandex.uz/maps/10335/tashkent/stops/1543141586/?ll=69.279737%2C41.311151&tab=overview&utm_medium=mapframe&utm_source=maps&z=12" style="color:#eee;font-size:12px;position:absolute;top:14px;">Чиланзар — Яндекс.Карты</a><iframe src="https://yandex.uz/map-widget/v1/-/CCUimWeW1C" width="100%" height="400" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe></div>

<!--			<div id="mapBox" class="mapBox" data-lat="40.701083" data-lon="-74.1522848" data-zoom="13" data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."-->
<!--			 data-mlat="40.701083" data-mlon="-74.1522848">-->
<!--			</div>-->
			<br>
			<div class="row">
				<div class="col-lg-3">
					<div class="contact_info">
						<div class="info_item">
							<i class="lnr lnr-home"></i>
							<h6>{% trans 'Mirzo Ulugbek Tumani 16-28' %}</h6>
<p></p>
						</div>
						<div class="info_item">
							<i class="lnr lnr-phone-handset"></i>
							<h6><a href="#">(90) 990-33-30</a></h6>
							<p></p>
<!--							<p>Mon to Fri 9am to 6 pm</p>-->
						</div>
						<div class="info_item">
							<i class="lnr lnr-envelope"></i>
							<h6><a href="#">sotti@mail.ru</a></h6>
							<p></p>
<!--							<p>Send us your query anytime!</p>-->
						</div>
					</div>
				</div>
				<div class="col-lg-9">
					<form class="row contact_form"  method="POST" style="display: flex;justify-content: space-around;">
						{% csrf_token %}
						<div class="col-md-6 text-right" style="float:right">
							<div class="form-group">
								<input type="text" class="form-control" id="name" name="name" placeholder="{% trans 'Enter your name' %}" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'">
							</div>
							<div class="form-group">
								<input type="email" class="form-control" id="email" name="email" placeholder="{% trans 'Enter email address' %}" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
							<div class="form-group">
								<textarea class="form-control" name="message" id="message" rows="1" placeholder="{% trans 'Enter Message' %}" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"></textarea>
							</div>
							<button type="submit" value="submit" class="primary-btn">{% trans 'Send Message' %}</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/history.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
  <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>{% trans 'Purchase history' %}</h1>
                    <nav class="d-flex align-items-center">
                        <a href="{% url 'contact:home' %}">{% trans 'Home' %}<span class="lnr lnr-arrow-right"></span></a>
                        <a href="#">{% trans 'Purchase history' %}</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
<br>
<div class="container">
    <table class="table table-bordered">
        <tr>
            <th>{% trans 'Quantity' %}</th>
            <th>{% trans 'id' %}</th>
            <th>{% trans 'Products' %}</th>
            <th>{% trans 'Price' %}</th>
            <th>{% trans 'Created_at' %}</th>
        </tr>
        {% for order in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                {% for product in order.products.all %}
                 <td>{{ product.sku }}</td>
                 {% endfor %}
                <td style="width:290px">
                    {% for product in order.products.all %}
                     <img src="{{ product.image.url  }}" style="width:50%" alt="">  <li style="list-style-type:none">{{ product.title }}</li>
                    {% endfor %}
                </td>

                <td>{{ order.price }}00som</td>
                <td>{{ order.created_at }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/login.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>{% trans 'Login/Register' %}</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'contact:home' %}">{% trans 'Home' %}<span class="lnr lnr-arrow-right"></span></a>
						<a href="#">{% trans 'Login/Register' %}</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Login Box Area =================-->
	<section class="login_box_area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="login_box_img">
						<img class="img-fluid" src="{% static 'img/login.jpg' %}" alt="">
						<div class="hover">
							<h4>New to our website?</h4>
							<p>There are advances being made in science and technology everyday, and a good example of this is the</p>
							<a class="primary-btn" href="#">Create an Account</a>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="login_form_inner">
						<h3>Log in to enter</h3>
						<form class="row login_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" id="name" name="name" placeholder="Username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'">
							</div>
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" id="name" name="name" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
							</div>
							<div class="col-md-12 form-group">
								<div class="creat_account">
									<input type="checkbox" id="f-option2" name="selector">
									<label for="f-option2">Keep me logged in</label>
								</div>
							</div>
							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="primary-btn">Log In</button>
								<a href="#">Forgot Password?</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Login Box Area =================-->
{% endblock %}

templates/products_filter.html
{% load i18n %}
<style>
    .a-active {
        color:#ffba00 !important
    }
</style>

<div class="col-xl-3 col-lg-4 col-md-5">
    <a style="color:#000;" href="{% url 'products:lists' %}">
        <button class="btn btn2 w-100" style="background-color:#ffba00">
            <img class="p-2" src="https://img.icons8.com/material-outlined/24/000000/broom.png"/>{% trans 'Clear filter' %}</button></a>

            <div class="sidebar-categories">
                  <div class="common-filter">
                      <br>
                    <div class="head">{% trans 'Price' %}</div>
                      <br>
                    <input type="text" class="js-range-slider" style="background-color:white"/>
                </div>
                <br>
                <div class="head" id="men">{% trans 'Categories' %}</div>
                <ul class="main-categories">
                    <li class="main-nav-list">
                        {% for categories in category %}
                         <a {% if request.GET.category == categories.pk|stringformat:'i' %}class="a-active"{% endif %} onclick="addUrlParameter('category', '{{ categories.pk }}')" style="cursor:pointer">
                            <span class="lnr lnr-arrow-right"></span>{{ categories.title }}<span
                                class="number"></span></a>
                        {% endfor %}
                    </li>
                </ul>
                <br>
            </div>
            <div class="sidebar-categories">
                <div class="head">{% trans 'Brands' %}</div>
                <ul class="main-categories">
                    <li class="main-nav-list">
                         {% for brand in brands %}
                        <a {% if request.GET.brand == brand.pk|stringformat:'i' %}class="a-active"{% endif %}  onclick="addUrlParameter('brand', '{{ brand.pk }}')" style="cursor:pointer">
                            <span class="lnr lnr-arrow-right"></span>{{ brand.title }}<span
                                class="number"></span></a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
            <div class="sidebar-filter mt-50">
                <div class="sidebar-categories">
                    <div class="head" style="color:#fff">{% trans 'Tags' %}</div>
                    <ul class="main-categories">
                        <li class="main-nav-list">
                            {% for tag in tags %}
                             <a {% if request.GET.tag == tag.pk|stringformat:'i' %}class="a-active"{% endif %}  onclick="addUrlParameter('tag', '{{ tag.pk }}')" style="cursor:pointer">
                                <span class="lnr lnr-arrow-right"></span>{{ tag.title }}<span
                                    class="number">(53)</span></a>
                            {% endfor %}
                        </li>
                    </ul>
                </div>
                <br>
            </div>
        </div>

templates/shopping-cart.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% load mytags %}

{% block content %}
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>{% trans 'Shopping-cart' %}</h1>
                <nav class="d-flex align-items-center">
                    <a href="{% url 'contact:home' %}">{% trans 'Home' %}<span class="lnr lnr-arrow-right"></span></a>
                    <a href="#">{% trans 'Shopping-cart' %}</a>
<!--                    <a href="category.html">Fashon Category</a>-->
                </nav>
            </div>
        </div>
    </div>
</section>

    <!-- Shopping Cart Section Begin -->
<br>
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th>{% trans 'Product' %}</th>
                                    <th>{% trans 'Quantity' %}</th>
                                    <th>{% trans 'Total' %}</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for product in object_list %}
                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img src="{{ product.image.url }}" style="width:50%" alt="">

                                        </div>
                                        <div class="product__cart__item__pic">
                                           <p>{{ product.title }}</p>
                                            <h5>{{ product.real_price }}som</h5>
                                        </div>
                                    </td>
                                    <td class="quantity__item">
                                        <div class="quantity">
                                            <div class="pro-qty-2">
                                                <input class="product-counter" data-input-id="{{ forloop.counter0 }}" id="count_{{ forloop.counter0 }}" type="text" value="1">
                                            </div>
                                        </div>
                                    </td>
                                    <td id="price_{{ forloop.counter0 }}" class="cart__price">{{ product.real_price }}som</td>
                                    <td class="cart__close">
                                        <a href="{% url 'products:add-cart' pk=product.pk %}?next={{ request.path }}?{{request.GET.urlencode}}">
                                             <i class="fa fa-close"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__total">
                        <h6>{% trans 'Cart total' %}</h6>
                        <ul>
                            <li>{% trans 'Total' %} <span>{% get_cart_sum request %}.000som</span></li>
                        </ul>
                        <a href="{% url 'orders:create' %}" class="primary-btn">{% trans 'Proceed to checkout' %}</a>
                    </div>
                </div>
            </div>
            <br>
        </div>
    </section>
    <!-- Shopping Cart Section End -->

{% endblock %}
{% block extra_js %}
<script>
   $('product-counter').on('change', function (e) {
        console.log(e)
   });
</script>
{% endblock %}

templates/wishlist.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% load mytags %}
{% block content %}
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>{% trans 'Wishlist Page' %}</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'contact:home' %}">{% trans 'Home' %}<span class="lnr lnr-arrow-right"></span></a>
						<a href="#">{% trans 'Wishlist' %}</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
<div class="container">
    <section class="lattest-product-area pb-40 category-list">
                <div class="row">
                    {% for product in object_list %}
                    <div class="col-lg-4 col-md-6">
                        {% include 'layouts/product_block.html' %}
                    </div>
                    {% endfor %}
                </div>
            </section>
</div>
<div class="container">
    <div class="row">
      <div class="pagination m-auto">

<!--                    <a href="#" class="prev-arrow"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>-->
                    {% for page in page_obj.paginator.page_range %}

                        <a {% if page == page_obj.number %}class="active"{% endif %} onclick="addUrlParameter('page', '{{ page }}')" style="cursor:pointer;margin-top:60%">{{ page }}</a>
                    {% endfor %}
<!--                    <a href="#" class="next-arrow"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>-->
                </div>
</div>
<BR>
</div>


{% endblock %}